# Filebeat - collect logs ONLY from orion-microcrm project containers
# Uses autodiscover to scope to one Docker Compose project, not the whole server
#
# BEAT_COMPOSE_PROJECT: env var for project name (default orion-microcrm)

filebeat.inputs: []

filebeat.autodiscover:
  enabled: true
  providers:
    - type: docker
      hints.enabled: false
      templates:
        - condition:
            contains:
              docker.container.name: "orion-microcrm"
          config:
            - type: filestream
              id: container-${data.docker.container.id}
              paths:
                - /var/lib/docker/containers/${data.docker.container.id}/*.log
              parsers:
                - container: ~
              processors:
                - add_docker_metadata:
                    host: "unix:///var/run/docker.sock"

# Output to Logstash
output.logstash:
  hosts: ["logstash:5044"]

output.elasticsearch:
  enabled: false

logging.level: info
logging.to_files: false
