input {
    file {
        path => "/var/log/app/spring.log"
        start_position => "beginning"
    }
}

filter {
    grok {
        match => { "message" => '%{TIMESTAMP_ISO8601:timestamp}. %{WORD:loglevel} %{GREEDYDATA:message}' }
    }
}

output {
    stdout {
        codec => json
    }
    elasticsearch {
        hosts => ["elasticsearch:9200"]
        index => "micro-crm-back-logs-%{+YYYY.MM.dd}"
        action => "create"
        user => "elastic"
        password => "${ELASTICSEARCH_PASSWORD}"
    }
}